### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1 in elasticsearch running 

### ISSUE THREAD

**Issue by Vinaymuthanna** [AgileWorksOrg/elasticsearch-river-csv#42]
[2014-12-30 10:03:35,887][ERROR][org.agileworks.elasticsearch.river.csv.CSVRiver] [Lacuna] [csv][my_csv_river] Error has occured during processing file 'PDUserDeviceDataTable.csv.processing' , skipping line: '[9999249575";"968";"cisco_user1";"00:12:F3:1C:02:6A";"2";"484";"0";"27.6";"48.4";"1419836497";"20.0";"46.0";"15.0";"56.0";"1000";"500";"12.8396621";"77.6616388]' and continue in processing
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.codehaus.groovy.runtime.BytecodeInterface8.objectArrayGet(BytecodeInterface8.java:360)
	at org.agileworks.elasticsearch.river.csv.OpenCSVFileProcessor.processDataLine(OpenCSVFileProcessor.groovy:72)
	at org.agileworks.elasticsearch.river.csv.OpenCSVFileProcessor.this$2$processDataLine(OpenCSVFileProcessor.groovy)
	at org.agileworks.elasticsearch.river.csv.OpenCSVFileProcessor$this$2$processDataLine.callCurrent(Unknown Source)
	at org.agileworks.elasticsearch.river.csv.OpenCSVFileProcessor.process(OpenCSVFileProcessor.groovy:49)
	at org.agileworks.elasticsearch.river.csv.CSVConnector.processAllFiles(CSVConnector.groovy:47)
	at org.agileworks.elasticsearch.river.csv.CSVConnector.run(CSVConnector.groovy:20)
	at java.lang.Thread.run(Thread.java:745)
the curl command used to create the index 

Use the following command to create an index.
#
curl -XPUT localhost:9200/_river/my_csv_river/_meta -d '
{
    "type" : "csv",
    "csv_file" : {
        "folder" : "/home/paqs/Downloads/kibana/dec",
        "filename_pattern" : ".*\\.csv$",
        "poll":"1m",
        "fields" : [
           "Sno",
           "userld",
           "userName",
           "deviceld",
           "deviceCurrentMode",
           "co2Level",
           "dustLevel",
           "temperature",
           "relativeHumidity",
           "timeStamp",
           "tempLow",
           "tempHigh",
           "rhLow",
           "rhHigh",
           "dust",
           "pollution",
           "latitude",
           "longitude"
        ],
        "first_line_is_header" : "false",
        "field_separator" : ",",
        "escape_character" : "\\",
        "quote_character" : "\"",
        "field_id" : "id",
        "field_timestamp" : "imported_at",
        "concurrent_requests" : "1",
        "charset" : "UTF-8",
        "script_before_file": "/home/paqs/Downloads/kibana/dec/before_file.sh",
        "script_after_file": "/home/paqs/Downloads/kibana/dec/after_file.sh",
        "script_before_all": "/home/paqs/Downloads/kibana/dec/before_all.sh",
        "script_after_all": "/home/paqs/Downloads/kibana/dec/after_all.sh"
    },
    "index" : {
        "index" : "decdevicedata",
        "type" : "alert",
        "bulk_size" : 1000,
        "bulk_threshold" : 10
    }
}'

#
# 4 Create a mapping
#
curl -XPUT http://localhost:9200/decdevicedata -d '
{
    "settings" : {
        "number_of_shards" : 1
    },
    "mappings" : {
        "alert" : {
            "properties" : {
            "Sno": {"type" : "integer"},
            "co2Level" : {"type" : "integer"},
            "deviceCurrentMode" : {"type" : "integer"},
            "deviceld"  : {"type" : "string"},
            "dust"  : {"type" : "integer"},
            "dustLevel" : {"type" : "integer"},
            "latitude": {"type" : "integer"},
            "longitude": {"type" : "integer"},
            "pollution" : {"type" : "integer"},
            "relativeHumidity" : {"type" : "float"},
            "rhLow": {"type" : "float"},
            "rhHigh": {"type" : "float"},
            "temperature": {"type" : "float"},
            "tempLow": {"type" : "float"},
            "tempHigh": {"type" : "float"},
            "timeStamp" : {"type" : "date", "ignore_malformed" : true, "format" : "dateOptionalTime"},
            "userld" : {"type" : "integer"},
            "userName" : {"type" : "string"}      
                    
            }
        }
    }
}'

**Comment by vtajzich** [comment]
I would say your csv doesn't contains correct data. The line has too few columns. Line is mentioned in stacktrace so you should be able to identify it.
